### ISSUE TITLE
Why API>=15 ?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [lvillani/android-cropimage#31] opened 2015-01-20 23:43 UTC
I think it works fine with API14 , maybe even lower.
I'd also like to ask: how does the library work? It seem to barely use any heap-memory.

**Comment by lvillani** [comment] 2015-01-21 09:11
> On 21 Jan 2015, at 00:43, AndroidDeveloperLB <notifications@github.com> wrote:
> 
> I think it works fine with API14 , maybe even lower.

API level 14 isn’t even listed in the Platform Version dashboard. The code was extracted from AOSP when it was at API Level 15, hence the constraint. Not a good reason, I know.

> I'd also like to ask: how does the library work? It seem to barely use any heap-memory.

I’m the wrong person to ask. I extracted it from AOSP but didn’t delve into the details.

--
Lorenzo Villani - lorenzo@villani.me   | http://lorenzo.villani.me
Develer S.r.l.  - lvillani@develer.com | http://www.develer.com
Software Solutions
Tel: +39 055-3984627 - int. 239
Fax: +39 055-3980808

**Comment by lvillani** [comment] 2015-01-21 09:12
Not a bug nor a real issue. Closing.

**Closed by lvillani** 2015-01-21 09:12 UTC

**Comment by AndroidDeveloperLB** [comment] 2015-01-21 09:17
I know it's not an issue, but there is no way here for me to set what it is.
Can you please check it though, and maybe set a new minimal value for it ? I've tested on the emulator and it seems to work fine...

**Comment by lvillani** [comment] 2015-01-21 09:30
> On 21 Jan 2015, at 10:17, AndroidDeveloperLB <notifications@github.com> wrote:
> 
> I know it's not an issue, but there is no way here for me to set what it is.

You can fork the project, change the requirements and add the forked version to your project.

> Can you please check it though, and maybe set a new minimal value for it ? I've tested on the emulator and it seems to work fine…

I’m afraid I can’t spend time on this project for the time being due to other commitments. I am willing to lower the requirement and add you as a contributor if you thoroughly test this on API level 14 (or lower) /on real hardware/ and commit to maintain the project for API level <= 14, fixing any issue that may arise on there.

I’m sorry if this sounds a bit harsh, but my time is really constrained and I can’t do anything beside some bug fixing for major issues.

--
Lorenzo Villani - lorenzo@villani.me   | http://lorenzo.villani.me
Develer S.r.l.  - lvillani@develer.com | http://www.develer.com
Software Solutions
Tel: +39 055-3984627 - int. 239
Fax: +39 055-3980808

**Comment by AndroidDeveloperLB** [comment] 2015-01-21 09:33
@lvillani No that's ok. Thank you for the hard work.
May I ask how did you import it? Did it take a long time to do it?
I remember I've tried to import the contacts/People app from official Android code, but failed, as there were a lot of errors.

**Comment by BatDroid** [comment] 2015-04-18 14:37
well even if i fork the project and change the min sdk to 14 i have to add it to my project locally, if there was a maven repository for that i would be thanksful
